# Generated by Django 2.2.3 on 2019-07-23 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Only letters are allowed.')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Only letters are allowed.')], verbose_name='last name'),
        ),
    ]
