# Generated by Django 2.2.3 on 2019-07-16 14:17

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(default='hxt365.resume@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='username',
            field=models.CharField(default='hxt365', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
